export interface QuickPrompt {
  id: string;
  label: string;
  body: string;
}

const REMIND = [
  "Summarize this conversation in a compact status card.",
  "",
  "**Format (markdown):**",
  "",
  "### 🎯 Goal",
  "One sentence — what the user set out to do.",
  "",
  "### 🔍 Root cause / key finding",
  "1–2 sentences on the actual issue (not symptoms). Include the critical number/path.",
  "",
  "### ✏️ Changes",
  "- `path/to/file.ts` — one-line description",
  "- `path/to/other.ts` — one-line description",
  "",
  "### ⏭️ Next step",
  "One sentence: what the user needs to do now (restart, review, test, nothing).",
  "",
  "**Rules:**",
  "- Skip sections that don't apply (write nothing, not \"N/A\").",
  "- Each line ≤ 100 chars. Total ≤ 150 words.",
  "- File paths use backticks. No prose preamble, no closing summary.",
].join("\n");

const CUT_FLUFF = [
  "CRITICAL — MUST FOLLOW IN EVERY RESPONSE WITHOUT EXCEPTION:",
  "",
  "- Short sentences only (3-6 words).",
  "- Zero filler or preamble. Never start with \"I'll\", \"Let me\", \"Sure\", \"Great\", etc.",
  "- Tool first, result first. Explain only if explicitly asked.",
  "- Violating this is a failure regardless of task quality.",
].join("\n");

const PR_REVIEW = [
  "Check if all CI/review runs are finished for this PR. If not, wait until they complete before proceeding.",
  "",
  "Fetch all review comments from the PR. Present a numbered summary table:",
  "",
  "| # | Author | File | Issue | Severity |",
  "|---|--------|------|-------|----------|",
  "",
  "Severity levels (your assessment):",
  "- **bug** — will crash or produce wrong results in production",
  "- **logic** — incorrect behavior under specific conditions",
  "- **robustness** — fragile code, missing guard, works today but breaks if assumptions change",
  "- **style** — naming, structure, readability — skip unless explicitly requested",
  "",
  "For each comment:",
  "1. Read the actual code and surrounding context — don't trust the suggestion blindly",
  "2. Classify: real bug / valid improvement / false positive / style nitpick / already handled",
  "3. Not all suggestions are worth implementing — automated reviewers produce false positives",
  "",
  "For each real fix:",
  "- Verify the bug exists by reading the code",
  "- Fix it",
  "- Trace callers and check related tests — make sure the fix doesn't break anything",
  "- Write or update tests if the fix changes behavior",
  "- Run unit tests after each fix",
  "",
  "If unsure whether a fix is correct or needed — ask me before implementing.",
  "",
  "After all fixes:",
  "- Run full quality checks (ruff format, ruff check, mypy, pytest)",
  "- Commit all fixes in one commit, push",
  "- Reply to each comment individually under its conversation (not as a single PR comment)",
  "- Resolve all conversations",
  "",
  "Finally, repeat the summary table with resolution:",
  "",
  "| # | Issue | Severity | Resolution | Detail |",
  "|---|-------|----------|------------|--------|",
  "",
  "Resolution values: `fixed` / `fixed (asked user)` / `not a bug` / `already handled` / `style — skipped`",
].join("\n");

const CHANGE_SUMMARY = [
  "Produce a \"Code Change Summary\" for the work done on this branch vs. main.",
  "",
  "Run, in parallel where independent:",
  "- `git rev-parse --abbrev-ref HEAD`",
  "- `git rev-list --left-right --count main...HEAD`",
  "- `git diff --stat main...HEAD`",
  "- `git diff --numstat main...HEAD`",
  "- `git log main..HEAD --oneline`",
  "- `git status --porcelain`",
  "- the project's test / lint / typecheck commands (infer from package.json / pyproject.toml / etc.)",
  "",
  "Emit **exactly** this markdown template:",
  "",
  "## Code Change Summary — <branch>",
  "",
  "### Verification",
  "- Tests:  <passed>/<total>, <skipped> skipped",
  "- Lint:   <clean | N issues>",
  "- Types:  <clean | N issues>",
  "- Build:  <✅ | ❌ | skipped>",
  "- Branch: <branch>",
  "- Base:   main (<N> ahead, <M> behind)",
  "- Dirty:  <N uncommitted files | clean>",
  "",
  "### Stats",
  "- Files:   +<N> created / ~<N> modified / -<N> deleted",
  "- LOC:     +<N> / -<N>",
  "- Tests:   +<N> added / ~<N> modified",
  "- Commits: <N>",
  "",
  "### Touched Areas",
  "```",
  "<ASCII diagram of top-level modules touched; arrows for dependencies>",
  "```",
  "",
  "### By Subsystem",
  "- **<path>**: <one-line what changed>",
  "",
  "### Tests",
  "- Added:    <file> (<N> cases)",
  "- Modified: <file>",
  "",
  "### Public Surface Changes",
  "- New/changed API endpoints, WS message types, exports, config keys, env vars.",
  "- Write \"none\" if none.",
  "",
  "### Risk / Boundaries Crossed",
  "- DB migrations, schema, protocol, auth, perf-hot paths. \"none\" if none.",
  "",
  "### Out of Scope / Not Changed",
  "- Bullets of things intentionally skipped.",
  "",
  "### Commits",
  "- <sha> <subject>",
  "",
  "**Rules:**",
  "- Each bullet ≤ 1 line.",
  "- Always keep: Verification, Stats, Touched Areas, Commits. Omit optional sections when empty.",
  "- Do NOT paste raw diff hunks.",
  "- Use ASCII only in the diagram (no Mermaid, no unicode boxes beyond `┌ ─ ┐ │ └ ┘ ↓ ← → ↑`).",
].join("\n");

const SELF_IMPROVE = [
  "# Self-improve guidance",
  "",
  "You are improving your own operating instructions. Not formatting — actual quality. Diagnose from this conversation, then fix the files.",
  "",
  "## Phase 1: Diagnose",
  "",
  "Review the current conversation — you already have it in context. Look for patterns across the whole session, not just the last turn. Also read:",
  "- `~/.claude/projects/.../memory/*.md`",
  "- `CLAUDE.md` and `~/.claude/CLAUDE.md`",
  "",
  "Answer these before touching any file:",
  "1. What mistakes recurred in this session?",
  "2. What rules exist but are routinely ignored?",
  "3. What situations arise that have no rule?",
  "4. What rules are vague enough to misapply?",
  "5. What content is never read because it's buried?",
  "",
  "Write findings as a short list. Then proceed.",
  "",
  "## Phase 2: Fix",
  "",
  "### Rules",
  "- Add missing rules exposed by Phase 1. Concrete only — number, path, or exact string. No \"reasonable\" or \"good\".",
  "- Remove rules that exist but aren't followed (they're noise). If a rule keeps being violated, rewrite it sharper or delete it.",
  "- Deduplicate: one truth per rule, one location.",
  "",
  "### Structure",
  "- CLAUDE.md ≤ 150 lines. Extract stable verbose content to `docs/<topic>.md`, link inline.",
  "- Global `~/.claude/CLAUDE.md`: add `##` headers, fix typos, remove anything redundant with project CLAUDE.md.",
  "- Memory: delete entries that describe resolved state or duplicate CLAUDE.md verbatim.",
  "",
  "### Platform hygiene",
  "- Run `uname`. Remove any OS-specific blocks that don't match.",
  "",
  "### Vestigial content",
  "- Remove placeholder sections (\"When X, update this file…\" with no content).",
  "- Remove rules that describe the obvious (e.g. \"write good code\").",
  "",
  "## Phase 3: Gaps",
  "",
  "After fixing what exists, add what's missing:",
  "",
  "```",
  "## Guidelines",
  "",
  "- **CLAUDE.md = index only.** Verbose stable content → `docs/`. Link from CLAUDE.md.",
  "- **One truth per rule.** Rule in global → not repeated in project.",
  "- **Concrete over vague.** Every constraint: number, path, or exact string.",
  "- **Rules must be followed or removed.** A rule violated repeatedly is noise.",
  "- **Memory = surprises only.** Not what `git log` answers. Only non-obvious decisions.",
  "- **Platform-guard or remove.** OS-specific blocks must match `uname` or be deleted.",
  "```",
  "",
  "## Output",
  "",
  "Per file: bullet list of changes + one-line reason each. Show only modified sections. Apply directly.",
  "",
  "Communication: short sentences, no preamble, tool first.",
].join("\n");

const PROPOSE_TITLE = [
  "Generate a concise title for this conversation and set it as the session name.",
  "",
  "Rules:",
  "- 3-7 words. Noun phrase or gerund. Present tense. No period.",
  "- Capture the core task, not the first message.",
  "- No quotes, no preamble, no explanation.",
  "- If there is an associated JIRA ticket (e.g. mentioned in the conversation, branch name, or commits), prefix the title with the ticket key and number, and include the ticket title if known. Format: `PROJ-123 Ticket title — your concise title`. If only the key is known, use `PROJ-123 your concise title`.",
  "",
  "Output format — your entire response must be EXACTLY this single line, nothing else:",
  "",
  "<<overlord:title>>Your title here<</overlord:title>>",
  "",
  "CRITICAL — the marker has TWO different tags:",
  "  - opening: <<overlord:title>>     (no slash)",
  "  - closing: <</overlord:title>>    (slash AFTER the second `<`, before `overlord`)",
  "Using the opening tag on both ends is the most common mistake — the server's regex `<<overlord:title>>([\\s\\S]+?)<<\\/overlord:title>>` will NOT match and the rename will silently fail.",
  "Before you submit: visually verify the closing tag contains `</` not `<<`.",
  "",
  "The Overlord server detects that marker in your last assistant message and renames the session automatically. Do not add any other text before or after.",
].join("\n");

const WHY_REFACTOR = [
  "# Why — higher-order code refactor",
  "",
  "Reason about why the code exists, not just its shape. For each lens below, apply to the current diff or working area, propose changes before touching anything, then implement.",
  "",
  "## 1. First-principles",
  "For each module in the diff, ask: what is its single responsibility? If you can't name it in one sentence, it's doing too much — split it. If two modules share a sentence, merge them.",
  "",
  "## 2. Deletion-first",
  "What could I delete from this codebase and have nothing important break? Rank candidates by (lines removed × risk of breakage⁻¹). Propose the top three before touching anything.",
  "",
  "## 3. Invariant-driven",
  "List the invariants this code is trying to maintain. For each, find the cheapest place to enforce it. Remove every check that duplicates an invariant already enforced upstream.",
  "",
  "## 4. Cost-of-change",
  "Identify the parts of this code most likely to change in the next six months, and the parts least likely. Push volatility outward (toward edges/config), push stability inward (toward core). Reshape accordingly.",
  "",
  "## 5. Boundary audit",
  "Where are the real boundaries in this system (process, network, trust, persistence)? Validate at boundaries only. Delete validation, error handling, and defensive coding that lives in the interior.",
  "",
  "## 6. The meta one",
  "Read this code and tell me what it would look like if the person who wrote it knew then what they know now. Then make that change.",
].join("\n");

export const QUICK_PROMPTS: QuickPrompt[] = [
  { id: 'remind',         label: 'Remind me where we left off', body: REMIND },
  { id: 'cut-fluff',      label: 'Cut the fluff',               body: CUT_FLUFF },
  { id: 'propose-title',  label: 'Generate a title',            body: PROPOSE_TITLE },
  { id: 'pr-review',      label: 'Handle PR Review Comments',   body: PR_REVIEW },
  { id: 'change-summary', label: 'Code Change Summary',         body: CHANGE_SUMMARY },
  { id: 'self-improve',   label: 'Self-improve guidance',       body: SELF_IMPROVE },
  { id: 'why-refactor',   label: 'Why — code refactor',         body: WHY_REFACTOR },
];
