export interface QuickPrompt {
  id: string;
  label: string;
  body: string;
}

const REMIND = [
  "Summarize this conversation in a compact status card.",
  "",
  "**Format (markdown):**",
  "",
  "### 🎯 Goal",
  "One sentence — what the user set out to do.",
  "",
  "### 🔍 Root cause / key finding",
  "1–2 sentences on the actual issue (not symptoms). Include the critical number/path.",
  "",
  "### ✏️ Changes",
  "- `path/to/file.ts` — one-line description",
  "- `path/to/other.ts` — one-line description",
  "",
  "### ⏭️ Next step",
  "One sentence: what the user needs to do now (restart, review, test, nothing).",
  "",
  "**Rules:**",
  "- Skip sections that don't apply (write nothing, not \"N/A\").",
  "- Each line ≤ 100 chars. Total ≤ 150 words.",
  "- File paths use backticks. No prose preamble, no closing summary.",
].join("\n");

const CUT_FLUFF = [
  "CRITICAL — MUST FOLLOW IN EVERY RESPONSE WITHOUT EXCEPTION:",
  "",
  "- Short sentences only (3-6 words).",
  "- Zero filler or preamble. Never start with \"I'll\", \"Let me\", \"Sure\", \"Great\", etc.",
  "- Tool first, result first. Explain only if explicitly asked.",
  "- Violating this is a failure regardless of task quality.",
].join("\n");

const PR_REVIEW = [
  "Check if all CI/review runs are finished for this PR. If not, wait until they complete before proceeding.",
  "",
  "Fetch all review comments from the PR. Present a numbered summary table:",
  "",
  "| # | Author | File | Issue | Severity |",
  "|---|--------|------|-------|----------|",
  "",
  "Severity levels (your assessment):",
  "- **bug** — will crash or produce wrong results in production",
  "- **logic** — incorrect behavior under specific conditions",
  "- **robustness** — fragile code, missing guard, works today but breaks if assumptions change",
  "- **style** — naming, structure, readability — skip unless explicitly requested",
  "",
  "For each comment:",
  "1. Read the actual code and surrounding context — don't trust the suggestion blindly",
  "2. Classify: real bug / valid improvement / false positive / style nitpick / already handled",
  "3. Not all suggestions are worth implementing — automated reviewers produce false positives",
  "",
  "For each real fix:",
  "- Verify the bug exists by reading the code",
  "- Fix it",
  "- Trace callers and check related tests — make sure the fix doesn't break anything",
  "- Write or update tests if the fix changes behavior",
  "- Run unit tests after each fix",
  "",
  "If unsure whether a fix is correct or needed — ask me before implementing.",
  "",
  "After all fixes:",
  "- Run full quality checks (ruff format, ruff check, mypy, pytest)",
  "- Commit all fixes in one commit, push",
  "- Reply to each comment individually under its conversation (not as a single PR comment)",
  "- Resolve all conversations",
  "",
  "Finally, repeat the summary table with resolution:",
  "",
  "| # | Issue | Severity | Resolution | Detail |",
  "|---|-------|----------|------------|--------|",
  "",
  "Resolution values: `fixed` / `fixed (asked user)` / `not a bug` / `already handled` / `style — skipped`",
].join("\n");

const CHANGE_SUMMARY = [
  "Produce a \"Code Change Summary\" for the work done on this branch vs. main.",
  "",
  "Run, in parallel where independent:",
  "- `git rev-parse --abbrev-ref HEAD`",
  "- `git rev-list --left-right --count main...HEAD`",
  "- `git diff --stat main...HEAD`",
  "- `git diff --numstat main...HEAD`",
  "- `git log main..HEAD --oneline`",
  "- `git status --porcelain`",
  "- the project's test / lint / typecheck commands (infer from package.json / pyproject.toml / etc.)",
  "",
  "Emit **exactly** this markdown template:",
  "",
  "## Code Change Summary — <branch>",
  "",
  "### Verification",
  "- Tests:  <passed>/<total>, <skipped> skipped",
  "- Lint:   <clean | N issues>",
  "- Types:  <clean | N issues>",
  "- Build:  <✅ | ❌ | skipped>",
  "- Branch: <branch>",
  "- Base:   main (<N> ahead, <M> behind)",
  "- Dirty:  <N uncommitted files | clean>",
  "",
  "### Stats",
  "- Files:   +<N> created / ~<N> modified / -<N> deleted",
  "- LOC:     +<N> / -<N>",
  "- Tests:   +<N> added / ~<N> modified",
  "- Commits: <N>",
  "",
  "### Touched Areas",
  "```",
  "<ASCII diagram of top-level modules touched; arrows for dependencies>",
  "```",
  "",
  "### By Subsystem",
  "- **<path>**: <one-line what changed>",
  "",
  "### Tests",
  "- Added:    <file> (<N> cases)",
  "- Modified: <file>",
  "",
  "### Public Surface Changes",
  "- New/changed API endpoints, WS message types, exports, config keys, env vars.",
  "- Write \"none\" if none.",
  "",
  "### Risk / Boundaries Crossed",
  "- DB migrations, schema, protocol, auth, perf-hot paths. \"none\" if none.",
  "",
  "### Out of Scope / Not Changed",
  "- Bullets of things intentionally skipped.",
  "",
  "### Commits",
  "- <sha> <subject>",
  "",
  "**Rules:**",
  "- Each bullet ≤ 1 line.",
  "- Always keep: Verification, Stats, Touched Areas, Commits. Omit optional sections when empty.",
  "- Do NOT paste raw diff hunks.",
  "- Use ASCII only in the diagram (no Mermaid, no unicode boxes beyond `┌ ─ ┐ │ └ ┘ ↓ ← → ↑`).",
].join("\n");

const SELF_IMPROVE = [
  "# Self-improve guidance",
  "",
  "You are improving your own operating instructions. Not formatting — actual quality. Read session history first, then fix the files.",
  "",
  "## Phase 1: Diagnose",
  "",
  "Read recent sessions to find patterns:",
  "- `~/.claude/history.jsonl` (last 50 entries)",
  "- `~/.claude/projects/.../memory/*.md`",
  "- `CLAUDE.md` and `~/.claude/CLAUDE.md`",
  "",
  "Answer these before touching any file:",
  "1. What mistakes recur across sessions?",
  "2. What rules exist but are routinely ignored?",
  "3. What situations arise that have no rule?",
  "4. What rules are vague enough to misapply?",
  "5. What content is never read because it's buried?",
  "",
  "Write findings as a short list. Then proceed.",
  "",
  "## Phase 2: Fix",
  "",
  "### Rules",
  "- Add missing rules exposed by Phase 1. Concrete only — number, path, or exact string. No \"reasonable\" or \"good\".",
  "- Remove rules that exist but aren't followed (they're noise). If a rule keeps being violated, rewrite it sharper or delete it.",
  "- Deduplicate: one truth per rule, one location.",
  "",
  "### Structure",
  "- CLAUDE.md ≤ 150 lines. Extract stable verbose content to `docs/<topic>.md`, link inline.",
  "- Global `~/.claude/CLAUDE.md`: add `##` headers, fix typos, remove anything redundant with project CLAUDE.md.",
  "- Memory: delete entries that describe resolved state or duplicate CLAUDE.md verbatim.",
  "",
  "### Platform hygiene",
  "- Run `uname`. Remove any OS-specific blocks that don't match.",
  "",
  "### Vestigial content",
  "- Remove placeholder sections (\"When X, update this file…\" with no content).",
  "- Remove rules that describe the obvious (e.g. \"write good code\").",
  "",
  "## Phase 3: Gaps",
  "",
  "After fixing what exists, add what's missing:",
  "",
  "```",
  "## Guidelines",
  "",
  "- **CLAUDE.md = index only.** Verbose stable content → `docs/`. Link from CLAUDE.md.",
  "- **One truth per rule.** Rule in global → not repeated in project.",
  "- **Concrete over vague.** Every constraint: number, path, or exact string.",
  "- **Rules must be followed or removed.** A rule violated repeatedly is noise.",
  "- **Memory = surprises only.** Not what `git log` answers. Only non-obvious decisions.",
  "- **Platform-guard or remove.** OS-specific blocks must match `uname` or be deleted.",
  "```",
  "",
  "## Output",
  "",
  "Per file: bullet list of changes + one-line reason each. Show only modified sections. Apply directly.",
  "",
  "Communication: short sentences, no preamble, tool first.",
].join("\n");

export const QUICK_PROMPTS: QuickPrompt[] = [
  { id: 'remind',         label: 'Remind me where we left off', body: REMIND },
  { id: 'cut-fluff',      label: 'Cut the fluff',               body: CUT_FLUFF },
  { id: 'pr-review',      label: 'Handle PR Review Comments',   body: PR_REVIEW },
  { id: 'change-summary', label: 'Code Change Summary',         body: CHANGE_SUMMARY },
  { id: 'self-improve',   label: 'Self-improve guidance',       body: SELF_IMPROVE },
];
