export interface QuickPrompt {
  id: string;
  label: string;
  body: string;
}

const REMIND = [
  "Summarize this conversation in a compact status card.",
  "",
  "**Format (markdown):**",
  "",
  "### 🎯 Goal",
  "One sentence — what the user set out to do.",
  "",
  "### 🔍 Root cause / key finding",
  "1–2 sentences on the actual issue (not symptoms). Include the critical number/path.",
  "",
  "### ✏️ Changes",
  "- `path/to/file.ts` — one-line description",
  "- `path/to/other.ts` — one-line description",
  "",
  "### ⏭️ Next step",
  "One sentence: what the user needs to do now (restart, review, test, nothing).",
  "",
  "**Rules:**",
  "- Skip sections that don't apply (write nothing, not \"N/A\").",
  "- Each line ≤ 100 chars. Total ≤ 150 words.",
  "- File paths use backticks. No prose preamble, no closing summary.",
].join("\n");

const CUT_FLUFF = [
  "CRITICAL — MUST FOLLOW IN EVERY RESPONSE WITHOUT EXCEPTION:",
  "",
  "- Short sentences only (3-6 words).",
  "- Zero filler or preamble. Never start with \"I'll\", \"Let me\", \"Sure\", \"Great\", etc.",
  "- Tool first, result first. Explain only if explicitly asked.",
  "- Violating this is a failure regardless of task quality.",
].join("\n");

const PR_REVIEW = [
  "Check if all CI/review runs are finished for this PR. If not, wait until they complete before proceeding.",
  "",
  "Fetch all review comments from the PR. Present a numbered summary table:",
  "",
  "| # | Author | File | Issue | Severity |",
  "|---|--------|------|-------|----------|",
  "",
  "Severity levels (your assessment):",
  "- **bug** — will crash or produce wrong results in production",
  "- **logic** — incorrect behavior under specific conditions",
  "- **robustness** — fragile code, missing guard, works today but breaks if assumptions change",
  "- **style** — naming, structure, readability — skip unless explicitly requested",
  "",
  "For each comment:",
  "1. Read the actual code and surrounding context — don't trust the suggestion blindly",
  "2. Classify: real bug / valid improvement / false positive / style nitpick / already handled",
  "3. Not all suggestions are worth implementing — automated reviewers produce false positives",
  "",
  "For each real fix:",
  "- Verify the bug exists by reading the code",
  "- Fix it",
  "- Trace callers and check related tests — make sure the fix doesn't break anything",
  "- Write or update tests if the fix changes behavior",
  "- Run unit tests after each fix",
  "",
  "If unsure whether a fix is correct or needed — ask me before implementing.",
  "",
  "After all fixes:",
  "- Run full quality checks (ruff format, ruff check, mypy, pytest)",
  "- Commit all fixes in one commit, push",
  "- Reply to each comment individually under its conversation (not as a single PR comment)",
  "- Resolve all conversations",
  "",
  "Finally, repeat the summary table with resolution:",
  "",
  "| # | Issue | Severity | Resolution | Detail |",
  "|---|-------|----------|------------|--------|",
  "",
  "Resolution values: `fixed` / `fixed (asked user)` / `not a bug` / `already handled` / `style — skipped`",
].join("\n");

const CHANGE_SUMMARY = [
  "Produce a \"Code Change Summary\" for the work done on this branch vs. main.",
  "",
  "Run, in parallel where independent:",
  "- `git rev-parse --abbrev-ref HEAD`",
  "- `git rev-list --left-right --count main...HEAD`",
  "- `git diff --stat main...HEAD`",
  "- `git diff --numstat main...HEAD`",
  "- `git log main..HEAD --oneline`",
  "- `git status --porcelain`",
  "- the project's test / lint / typecheck commands (infer from package.json / pyproject.toml / etc.)",
  "",
  "Emit **exactly** this markdown template:",
  "",
  "## Code Change Summary — <branch>",
  "",
  "### Verification",
  "- Tests:  <passed>/<total>, <skipped> skipped",
  "- Lint:   <clean | N issues>",
  "- Types:  <clean | N issues>",
  "- Build:  <✅ | ❌ | skipped>",
  "- Branch: <branch>",
  "- Base:   main (<N> ahead, <M> behind)",
  "- Dirty:  <N uncommitted files | clean>",
  "",
  "### Stats",
  "- Files:   +<N> created / ~<N> modified / -<N> deleted",
  "- LOC:     +<N> / -<N>",
  "- Tests:   +<N> added / ~<N> modified",
  "- Commits: <N>",
  "",
  "### Touched Areas",
  "```",
  "<ASCII diagram of top-level modules touched; arrows for dependencies>",
  "```",
  "",
  "### By Subsystem",
  "- **<path>**: <one-line what changed>",
  "",
  "### Tests",
  "- Added:    <file> (<N> cases)",
  "- Modified: <file>",
  "",
  "### Public Surface Changes",
  "- New/changed API endpoints, WS message types, exports, config keys, env vars.",
  "- Write \"none\" if none.",
  "",
  "### Risk / Boundaries Crossed",
  "- DB migrations, schema, protocol, auth, perf-hot paths. \"none\" if none.",
  "",
  "### Out of Scope / Not Changed",
  "- Bullets of things intentionally skipped.",
  "",
  "### Commits",
  "- <sha> <subject>",
  "",
  "**Rules:**",
  "- Each bullet ≤ 1 line.",
  "- Always keep: Verification, Stats, Touched Areas, Commits. Omit optional sections when empty.",
  "- Do NOT paste raw diff hunks.",
  "- Use ASCII only in the diagram (no Mermaid, no unicode boxes beyond `┌ ─ ┐ │ └ ┘ ↓ ← → ↑`).",
].join("\n");

export const QUICK_PROMPTS: QuickPrompt[] = [
  { id: 'remind',         label: 'Remind me where we left off', body: REMIND },
  { id: 'cut-fluff',      label: 'Cut the fluff',               body: CUT_FLUFF },
  { id: 'pr-review',      label: 'Handle PR Review Comments',   body: PR_REVIEW },
  { id: 'change-summary', label: 'Code Change Summary',         body: CHANGE_SUMMARY },
];
